# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2b8265a14c2ec5466e02bf871a2a43bf99a624fad222ec37f7705da163e56fe560f63a39d32043c5985467878bb9aea9727506b101f24c6173735676f9ed2db

test:
  secret_key_base: 2596c715750cee87882ca66b81e02295255075992a345a7a6e7b45e8246551337b7fec4bf986a04e448460d4ce86ac4c845fec560d86dd10be220061764b4326

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
